{% set name = "mache" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7101e41d8d14032f1173a0b54c76557c16ff62e1bd42a2141500d7e816bfaf58

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - lxml

test:
  imports:
    - mache

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://github.com/E3SM-Project/mache/README.rst
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - xylar
