{% set name = "mache" %}
{% set version = "1.20.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: 229fa5c6c937a30473973fa6aad06c20378c3da958c6ade730f38d614910ec34

build:
  number: 0
  noarch: python
  entry_points:
    - mache = mache.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - importlib_resources
    - jinja2
    - lxml
    - pyyaml
    - progressbar2
    - rsync

test:
  requires:
    - pip
  imports:
    - mache
  commands:
    - pip check
    - mache sync diags --help

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://github.com/E3SM-Project/mache/README.rst
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - xylar
