{% set name = "mache" %}
{% set version = "1.17.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8949089d20602ce85d184f52c45e516de38d4cdc79a0f21c208dc44852119229

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - mache = mache.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - importlib_resources
    - jinja2
    - lxml
    - pyyaml
    - progressbar2
    - rsync

test:
  requires:
    - pip
  imports:
    - mache
  commands:
    - pip check
    - mache sync diags --help

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://github.com/E3SM-Project/mache/README.rst
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - xylar
