{% set name = "mache" %}
{% set version = "1.2.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8386540de03d21566af1e24bcebeafd4cd9ec06f149839fb1fd395f7dec163cb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - lxml

test:
  imports:
    - mache

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://github.com/E3SM-Project/mache/README.rst
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - xylar
