{% set name = "mache" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: a8c1c6a013fa3ad151ef3b88db0c44d927760071fb3b24f1df59359f54c0c580

build:
  number: 0
  noarch: python
  entry_points:
    - mache = mache.__main__:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=60
  run:
    - python >=3.9
    - importlib_resources
    - jinja2
    - lxml
    - pyyaml
    - progressbar2
    - rsync

test:
  requires:
    - pip
  imports:
    - mache
  commands:
    - pip check
    - mache sync diags --help

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://docs.e3sm.org/mache/
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - altheaden
    - xylar
